import fs from'node:fs';import{execFileSync}from'node:child_process';
const T=[],ok=(n,f)=>T.push([n,f]),r=p=>fs.readFileSync(p,'utf8'),a=r('app.js'),h=r('index.html'),s=r('sw.js'),d=r('db.js'),c=r('styles.css');
for(const f of['app.js','db.js','sw.js','captcha-config.js'])ok(`JavaScript syntax: ${f}`,()=>execFileSync(process.execPath,['--check',f]));
ok('Manifest valid',()=>{const m=JSON.parse(r('manifest.webmanifest'));if(!m.name||!m.start_url||!m.icons?.length||!m.display)throw Error('manifest')});
ok('Service worker core cache files exist',()=>{for(const x of['./','./index.html','./styles.css?v=5.0','./app.js?v=5.0'])if(!s.includes(x))throw Error(x)});
ok('Service worker bypasses third-party traffic',()=>{if(!s.includes("url.origin!==self.location.origin"))throw Error('bypass')});
ok('No secret/service-role key embedded',()=>{if(/service_role|sb_secret_|TURNSTILE_SECRET/i.test(a+h+r('captcha-config.js')))throw Error('secret')});
ok('No duplicate HTML ids',()=>{const ids=[...h.matchAll(/\sid="([^"]+)"/g)].map(x=>x[1]),seen=new Set();for(const id of ids){if(seen.has(id))throw Error(id);seen.add(id)}});
ok('All simple #id selectors exist',()=>{for(const id of new Set([...a.matchAll(/\$\('#([A-Za-z][\w:-]*)'\)/g)].map(x=>x[1])))if(!h.includes(`id="${id}"`))throw Error(id)});
ok('Exactly one onboarding dialog',()=>{if((h.match(/id="onboardingDialog"/g)||[]).length!==1)throw Error('onboarding duplicate')});
ok('Account controls wired',()=>{for(const id of['signInBtn','signUpBtn','syncNowBtn','signOutBtn'])if(!h.includes(`id="${id}"`)||!a.includes(`#${id}`))throw Error(id)});
ok('Local CRUD exports exist',()=>{for(const x of['saveEntry','deleteEntry','clearEntries','bulkSave'])if(!d.includes(x))throw Error(x)});
ok('Encrypted backup strong crypto',()=>{for(const x of['PBKDF2',"hash:'SHA-256'",'AES-GCM'])if(!a.includes(x))throw Error(x)});
ok('Cloud fetch paginates',()=>{if(!a.includes('pageSize=1000')||!a.includes('.range('))throw Error('pagination')});
ok('Local fallback exists',()=>{if(!a.includes('Local logging still works'))throw Error('fallback')});
ok('Password recovery exists',()=>{for(const x of['PASSWORD_RECOVERY','updateUser({password})','passwordRecoveryDialog'])if(!(a+h).includes(x))throw Error(x)});
ok('Profiles table used',()=>{if(!a.includes(".from('profiles')"))throw Error('profiles')});
ok('CAPTCHA token sent',()=>{if(!a.includes('captchaToken:captcha'))throw Error('captcha')});
ok('Privacy and Terms exist',()=>{for(const x of['screen-privacy','screen-terms'])if(!h.includes(x))throw Error(x)});
ok('Account deletion clears local cloud state',()=>{for(const x of['removeItem(CLOUD_LAST_USER_KEY)','removeItem(CLOUD_SHADOW_KEY)','removeItem(CLOUD_DELETE_QUEUE_KEY)'])if(!a.includes(x))throw Error(x)});
ok('Accessibility polish exists',()=>{if(!h.includes('aria-live="polite"')||!c.includes('prefers-reduced-motion')||!c.includes('min-height:44px'))throw Error('a11y')});
ok('Six navigation items exist',()=>{const n=h.match(/<nav class="bottom-nav"[\s\S]*?<\/nav>/)?.[0]||'';for(const x of['home','log','history','insights','stats','settings'])if(!n.includes(`data-nav="${x}"`))throw Error(x)});
ok('Report disclaimer retained',()=>{if(!a.includes('does not diagnose a condition'))throw Error('disclaimer')});
let p=0;console.log('\nLog My Log QA — V5 public-beta suite\n');for(const[n,f]of T){try{f();p++;console.log(`✓ ${n}`)}catch(e){console.log(`✗ ${n}: ${e.message}`)}}console.log(`\n${p}/${T.length} passed; ${T.length-p} failed.`);if(p!==T.length)process.exit(1);
